### ISSUE TITLE
s3 private information in repo

### ISSUE THREAD

**Issue by silky** [fpco/wai-middleware-crowd#3]
i sent an email privately about this but haven't heard back, so i figure i'll report it here

the `travis.yml` file seems to have private info in it - https://github.com/fpco/wai-middleware-crowd/blob/master/.travis.yml

it should probably be removed and new keys generated, etc.

**Comment by snoyberg** [comment]
It contains the access key, which is not sensitive information. The secret key is encrypted.

**Comment by silky** [comment]
okay.

-- edit: this is what @snoyberg means, i believe - https://docs.travis-ci.com/user/encryption-keys

interesting, i clearly didn't know about that.
